### ISSUE TITLE
Error 'PopupBridge' in AST file in swift project

### ISSUE THREAD

**Issue by chaudharivishal4u** [braintree/popup-bridge-ios#15]
### General information

* SDK/Library version: 
* iOS Version and Device: 
* Integration type and version:

**Comment by chaudharivishal4u** [comment]
fatal error: module 'PopupBridge' in AST file '/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2MKVMOD5I8QBW/PopupBridge-YEJL8I59BA6Y.pcm' (imported by AST file '/Users/XYZ/Library/Developer/Xcode/DerivedData/ProjectName-bkdcfwlnwrlmwtcanuvfoqsbudsg/Build/Intermediates.noindex/PrecompiledHeaders/FoodX-Bridging-Header-swift_QHPYR8QT3M4A-clang_2MKVMOD5I8QBW.pch') is not defined in any loaded module map file; maybe you need to load '/ios_projects/ProjectName/Pods/Headers/Public/PopupBridge/PopupBridge.modulemap'?

**Comment by VitalikKizlov** [comment]
anyone knows how to fix such issues ? Has the same but with segment Appsflyer framework

**Comment by scannillo** [comment]
Hi @VitalikKizlov please open a new issue. But in order to help we need all of the following information:

**Integration Details (please complete the following information):**
 - Braintree SDK Version: [e.g. 5.13.0]
 - Environment: [e.g. Sandbox or Production]
 - iOS Version: [e.g. iOS 16.0]
 - Xcode Version: [e.g. Xcode 14.1]
 - Device: [e.g. iPhone 12]
 - Integration type & version: [e.g. CocoaPods 1.1.1, Carthage 0.18.1, Swift Package Manager 5.7.0]
 - Development Processor Type: [e.g. Intel, M1/ Apple Silicon]

**Describe the bug**
Description of what the bug is. Please include as many details as possible.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

**Expected behavior**
Description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
